# CarbonTrace Logstash pipeline
# Flow:  [poller]  --NDJSON over HTTP-->  Logstash  --->  Elasticsearch (emissions-live)

input {
  http {
    port => 8080
    codec => json_lines
  }
}

filter {
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
  mutate {
    remove_field => ["headers", "host", "@version", "user_agent", "http", "url", "event"]
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST:elasticsearch:9200}"]
    index => "emissions-live"
    manage_template => false
  }
}
