name: "Bad Bug"
description: "Something isn't working."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      placeholder: "Expected X, got Y."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1. ...\n2. ..."
    validations:
      required: false
