name: "Fancy new Feature"
description: "Propose work before starting it."
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: What are you building?
      placeholder: "One sentence."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Why are you building it ?
      placeholder: "To test your understanding of the feature if it fits well with the current scope"
    validations:
      required: true
