"""initial migration

Revision ID: 93cd4e11117a
Revises: 
Create Date: 2026-09-20 23:13:41.697204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cd4e11117a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_drafts')
    op.create_foreign_key(None, 'activity_records', 'facilities', ['facility_id'], ['id'])
    op.create_foreign_key(None, 'calculated_emissions', 'emission_factors', ['emission_factor_id'], ['id'])
    op.create_foreign_key(None, 'calculated_emissions', 'activity_records', ['activity_record_id'], ['id'])
    op.alter_column('facilities', 'facility_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('office', 'warehouse', 'data_center', 'manufacturing', name='facility_type_enum'),
               existing_nullable=True)
    op.alter_column('recommendations', 'rule_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('TopEmitters', 'SpikeDetect', 'AnomalyCoincidence', name='rule_type_enum'),
               existing_nullable=False)
    op.create_foreign_key(None, 'recommendations', 'facilities', ['facility_id'], ['id'])
    op.create_foreign_key(None, 'recommendations', 'periods', ['period_id'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'periods', ['baseline_period_id'], ['id'])
    op.create_foreign_key(None, 'scenarios', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.alter_column('recommendations', 'rule_id',
               existing_type=sa.Enum('TopEmitters', 'SpikeDetect', 'AnomalyCoincidence', name='rule_type_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('facilities', 'facility_type',
               existing_type=sa.Enum('office', 'warehouse', 'data_center', 'manufacturing', name='facility_type_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'calculated_emissions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'calculated_emissions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'activity_records', type_='foreignkey')
    op.create_table('ocr_drafts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('activity_record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_record_id'], ['activity_records.id'], name=op.f('ocr_drafts_activity_record_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ocr_drafts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ocr_drafts_pkey')),
    sa.UniqueConstraint('activity_record_id', name=op.f('ocr_drafts_activity_record_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
